[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "/blog"
  to = "/"
  force = true
[[redirects]]
  from = "https://taroshuntaro.me/admin"
  to = "https://taroshuntaro.me/404"
  force = true
  status = 404